package ar.com.ua.constant;

public class PermisosConstant {

	private PermisosConstant() {
	};

	// EMPLEADOS
	public static final String PERMISO_EMPLEADO_ALTA = "PERMISO_EMPLEADO_ALTA";
	public static final String PERMISO_EMPLEADO_BAJA = "PERMISO_EMPLEADO_BAJA";
	public static final String PERMISO_EMPLEADO_MODIFICACION = "PERMISO_EMPLEADO_MODIFICACION";
	public static final String PERMISO_EMPLEADO_LISTADO = "PERMISO_EMPLEADO_LISTADO";

	// USUARIOS
	public static final String PERMISO_USUARIO_ALTA = "PERMISO_USUARIO_ALTA";
	public static final String PERMISO_USUARIO_BAJA = "PERMISO_USUARIO_BAJA";
	public static final String PERMISO_USUARIO_MODIFICACION = "PERMISO_USUARIO_MODIFICACION";
	public static final String PERMISO_USUARIO_LISTADO = "PERMISO_USUARIO_LISTADO";

	// TABLA PARAMETRICA
	public static final String PERMISO_TABLAS_PARAMETRICAS_ALTA = "PERMISO_TABLAS_PARAMETRICAS_ALTA";
	public static final String PERMISO_TABLAS_PARAMETRICAS_BAJA = "PERMISO_TABLAS_PARAMETRICAS_BAJA";
	public static final String PERMISO_TABLAS_PARAMETRICAS_MODIFICACION = "PERMISO_TABLAS_PARAMETRICAS_MODIFICACION";
	public static final String PERMISO_TABLAS_PARAMETRICAS_LISTADO = "PERMISO_TABLAS_PARAMETRICAS_LISTADO";
}
